server:
  port: 8001

spring:
  application:
    name: user-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/duty
    password: 123456
    username: root

eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8000/eureka/,http://user:123456@localhost:9000/eureka/
  instance:
    prefer-ip-address: true
    ip-address: localhost
    virtual-host-name: user-client
info:
  app:
    name: eureka-client-user-8001
    virtual-host-name: user-client
  company:
    name: www.wang.com
  build:
    artifactId: "@project.artifactId@"
    version: "@project.version@"