server:
  port: 8001
spring:
  application:
    name: client
eureka:
  instance:
    status-page-url-path: /info
    health-check-url-path: /health
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    healthcheck:
      enabled: true
